<?php

/**
 * @file
 * Contains iq_blog.module.
 */

use Drupal\image\Entity\ImageStyle;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function iq_blog_theme($existing, $type, $theme, $path) {
  return [
    'node__iq_blog_post' => [
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function iq_blog_page_attachments_alter(array &$page) {

  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface && $node->gettype() == 'iq_blog_post') {

    $page['#attached']['html_head'][] = [
      [
        '#tag' => 'meta',
        '#attributes' => [
          "property" => "og:type",
          "content" => 'blog',
        ],
      ],
      'og:type',
    ];

    $page['#attached']['html_head'][] = [
      [
        '#tag' => 'meta',
        '#attributes' => [
          "property" => "og:title",
          "content" => $node->title->value,
        ],
      ],
      'og:title',
    ];

    if ($node->field_iq_lead->value) {
      $page['#attached']['html_head'][] = [
        [
          '#tag' => 'meta',
          '#attributes' => [
            "property" => "og:description",
            "content" => trim(preg_replace('/\s\s+/', ' ', strip_tags((string) $node->field_iq_lead->value))),
          ],
        ],
        'og:description',
      ];
    }

    $page['#attached']['html_head'][] = [
      [
        '#tag' => 'meta',
        '#attributes' => [
          "property" => "og:url",
          "content" => $node->toUrl()->setAbsolute()->toString(),
        ],
      ],
      'og:url',
    ];

    if ($node->field_iq_image && $node->field_iq_image->entity) {
      $imageUri = $node->field_iq_image->entity->field_media_image->entity->uri->value;
      if ($imageUri) {
        $style = ImageStyle::load('iq_og_image');
        $page['#attached']['html_head'][] = [
          [
            '#tag' => 'meta',
            '#attributes' => [
              "property" => "og:image",
              "content" => $style->buildUrl($imageUri),
            ],
          ],
          'og:image',
        ];
      }
    }
  }

}
