<?php

/**
 * @file
 * Contains iq_blog_like_dislike.module.
 */

/**
 * Implements hook_theme().
 */
function iq_blog_like_dislike_preprocess_node__iq_blog_post(&$variables) {
  $variables['#attached']['library'][] = 'iq_blog_like_dislike/blog-post-like-dislike';
}

/**
 * Implements hook_theme().
 */
function iq_blog_like_dislike_theme() {
  return [
    'iq_like_dislike' => [
      'variables' => [
        'likes' => NULL,
        'dislikes' => NULL,
        'like_url' => NULL,
        'dislike_url' => NULL,
        'entity_id' => NULL,
        'hide_dislike' => NULL,
      ],
    ],
  ];
}
